//
//  Icons.swift
//  Why am I so poor
//
//  Created by Mu Yu on 7/5/22.
//

import UIKit

class Icons {
    static var circle: String { "circle" }
    static var circleFill: String { "circle.fill" }
    static var flame: String { "flame" }
    static var flameFill: String { "flame.fill" }
    static var transfer: String { "arrow.2.squarepath" }
    static var lightbulb: String { "lightbulb" }
    static var dollarsignCircle: String { "dollarsign.circle" }
    static var dollarsignCircleFill: String { "dollarsign.circle.fill" }
    static var dollarSignArrowCirclePath: String { "dollarsign.arrow.circlepath" }
    static var plus: String { "plus" }
    static var eyeglasses: String { "eyeglasses" }
    static var sparkle: String { "sparkle" }
    static var sparkles: String { "sparkles" }
    static var cursorarrowRays: String { "cursorarrow.rays" }
    static var handsSparkles: String { "hands.sparkles" }
    static var handsSparklesFill: String { "hands.sparkles.fill" }
    static var plusCircle: String { "plus.circle" }
    static var plusCircleFill: String { "plus.circle.fill" }
    static var house: String { "house" }
    static var houseFill: String { "house.fill" }
    static var bedDouble: String { "bed.double" }
    static var bedDoubleFill: String { "bed.double.fill" }
    static var chartBar: String { "chart.bar" }
    static var chartBarFill: String { "chart.bar.fill" }
    static var chevronForward: String { "chevron.forward" }
    static var chevronBackward: String { "chevron.backward" }
    static var zzz: String { "zzz" }
    static var creditcard: String { "creditcard" }
    static var creditcardFill: String { "creditcard.fill" }
    static var creditcardCircle: String { "creditcard.circle" }
    static var creditcardCircleFill: String { "creditcard.circle.fill" }
    static var banknote: String { "banknote" }
    static var pencil: String { "pencil" }
    static var cart: String { "cart" }
    static var cartFill: String { "cart.fill" }
    static var giftcard: String { "giftcard" }
    static var questionmark: String { "questionmark" }
    static var person: String { "person" }
    static var personFill: String { "person.fill" }
    static var plusminus: String { "plusminus" }
    static var plusminusFill: String { "plusminus.fill" }
    static var plusminusCircle: String { "plusminus.circle" }
    static var clock: String { "clock" }
    static var clockFill: String { "clock.fill" }
    static var gearshape: String { "gearshape" }
    static var gearshapeFill: String { "gearshape.fill" }
    static var calendar: String { "calendar" }
    static var calendarCircleFill: String { "calendar.circle.fill" }
    static var calendarBadgePlus: String { "calendar.badge.plus" }
    static var calendarBadgeMinus: String { "calendar.badge.minus" }
    static var calendarBadgeClock: String { "calendar.badge.clock" }
    static var bell: String { "bell" }
    static var bellFill: String { "bell.fill" }
    static var bellbadge: String { "bell.badge" }
    static var bellbadgeFill: String { "bell.badge.fill" }
    static var tag: String { "tag" }
    static var tagFill: String { "tag.fill" }
    static var xmark: String { "xmark" }
    static var hammerFill: String { "hammer.fill" }
    static var forkKnife: String { "fork.knife" }
    static var cupAndSaucerFill: String { "cup.and.saucer.fill" }
    static var takeoutbagAndCupAndStraw: String { "takeoutbag.and.cup.and.straw" }
    static var takeoutbagAndCupAndStrawFill: String { "takeoutbag.and.cup.and.straw.fill" }
    static var boltFill: String { "bolt.fill" }
    static var wifi: String { "wifi" }
    static var dropFill: String { "drop.fill" }
    static var iphoneHomeButton: String { "iphone.homebutton" }
    static var phone: String { "phone" }
    static var phoneFill: String { "phone.fill" }
    static var magnifyingglass: String { "magnifyingglass" }
    static var magnifyingglassCircle: String { "magnifyingglass.circle" }
    static var magnifyingglassCircleFill: String { "magnifyingglass.circle.fill" }
    static var mic: String { "mic" }
    static var micFill: String { "mic.fill" }
    static var tvFill: String { "tv.fill" }
    static var bus: String { "bus" }
    static var carFill: String { "car.fill" }
    static var paperclip: String { "paperclip" }
    static var gift: String { "gift.fill" }
    static var externalDriveFill: String { "externaldrive.fill" }
    static var appleLogo: String { "applelogo" }
    static var terminal: String { "terminal" }
    static var terminalFill: String { "terminal.fill" }
    static var network: String { "network" }
    static var graduationCapFill: String { "graduationcap.fill" }
    static var airplane: String { "airplane" }
    static var tramFill: String { "tram.fill" }
    static var mapFill: String { "map.fill" }
    static var pillsFill: String { "pills.fill" }
    static var crossCaseFill: String { "cross.case.fill" }
    static var eyeFill: String { "eye.fill" }
    static var mouth: String { "mouth" }
    static var eyebrow: String { "eyebrow" }
    static var mouthFill: String { "mouth.fill" }
    static var filmFill: String { "film.fill" }
    static var ticketFill: String { "ticket.fill" }
    static var playTvFill: String { "play.tv.fill" }
    static var note: String { "note" }
    static var noteText: String { "note.text" }
    static var gamecontrollerFill: String { "gamecontroller.fill" }
    static var figureWalk: String { "figure.walk" }
    static var tshirtFill: String { "tshirt.fill" }
    static var shippingBoxFill: String { "shippingbox.fill" }
    static var scrollFill: String { "scroll.fill" }
    static var characterBubbleFill: String { "character.bubble.fill" }
    static var message: String { "message" }
    static var messageFill: String { "message.fill" }
    static var messageCircleFill: String { "message.circle.fill" }
    static var link: String { "link" }
    static var squareAndArrowUp: String { "square.and.arrow.up" }
    static var squareAndArrowUpCircleFill: String { "square.and.arrow.up.circle.fill" }
    static var textBookClosedFill: String { "text.book.closed.fill" }
    static var crossFill: String { "cross.fill" }
    static var heartFill: String { "heart.fill" }
    static var lineThreeHorizontalDecreaseCircle: String { "line.3.horizontal.decrease.circle" }
    static var lineThreeHorizontalDecreaseCircleFill: String { "line.3.horizontal.decrease.circle.fill" }
    static var mappinAndEllipse: String { "mappin.and.ellipse" }
}
